### ISSUE TITLE
README.md needs fixed.

### ISSUE THREAD

**Issue by eahrold** [sheagcraig/jss-recipes#11]
In the README.md you have this line ...

> These recipes are intended to be used with my jss-autopkg-addon. Grab the package installer from the releases section, and you're good to go.
 
Which I think needs updated to _JSSImporter_.

**Comment by sheagcraig** [comment]
Too true.

**Comment by sheagcraig** [comment]
I think you're looking at the master branch. It's correct in testing.

**Comment by eahrold** [comment]
Sure enough.
