### ISSUE TITLE
Extension Attribute not overridable...

### ISSUE THREAD

**Issue by everetteallen** [sheagcraig/jss-recipes#6]
Trying to write an override for the AdobeFlashPlayer.jss.recipe and it has an extension attribute in it's Process Key that is not overridable.  The override works but always returns error:

    A Python exception occurred during the execution of autopkg, see the console log for more details.
    [ERROR] IOError: [Errno 2] No such file or directory: u'/Users/serveradmin/Library/AutoPkg/RecipeOverrides/AdobeFlashPlayerExtensionAttribute.xml'

If I just do 
touch /Users/serveradmin/Library/AutoPkg/RecipeOverrides/AdobeFlashPlayerExtensionAttribute.xml
Then get:

    A Python exception occurred during the execution of autopkg, see the console log for more details.
    [ERROR] xml.etree.ElementTree.ParseError: no element found: line 1, column 0

So looking for a real xml file.  When I copy the one from the parent recipe repo works but the EA would be created which I don't want.
I am only familiar with overriding inputs so maybe I missed a way to suppress the creation of the EA?

**Comment by sheagcraig** [comment]
The extension attribute is not overrideable in that recipe at this point. I think you'd be better off just crafting your own AdobeFlashPlayer.jss.recipe to avoid the extension attribute. You could just copy mine and take out the extension_attributes section.

It's possible that I could add the feature to JSSImporter to turn on collection of plugins, which would remove the need for this extension attribute, but I'm guessing that's potentially even more problematic for some organizations.

Also, in the pipeline is the plan to put into a place an organization to manage an "official" or "default" set of jss recipes. One of the things I'll review before crafting the guidelines for that is whether it's feasible to make the extension attributes overrideable.

**Comment by everetteallen** [comment]
Shea,
Will do on Recipe. Future ability for "defaults" sounds great. Thanks for
considering the override features!
Everette



On Apr 23, 2015, at 8:38 AM, Shea Craig <notifications@github.com> wrote:

The extension attribute is not overrideable in that recipe at this point. I
think you'd be better off just crafting your own
AdobeFlashPlayer.jss.recipe to avoid the extension attribute. You could
just copy mine and take out the extension_attributes section.

It's possible that I could add the feature to JSSImporter to turn on
collection of plugins, which would remove the need for this extension
attribute, but I'm guessing that's potentially even more problematic for
some organizations.

Also, in the pipeline is the plan to put into a place an organization to
manage an "official" or "default" set of jss recipes. One of the things
I'll review before crafting the guidelines for that is whether it's
feasible to make the extension attributes overrideable.

—
Reply to this email directly or view it on GitHub
<https://github.com/sheagcraig/jss-recipes/issues/6#issuecomment-95572602>.
